import { Arz, Haber } from "./types";

export const mockArzlar: Arz[] = [
  {
    id: "mcard-metropal-2026",
    ticker: "MCARD",
    sirketAdi: "Metropal Kurumsal Hizmetler A.Ş.",
    slug: "metropal-kurumsal-hizmetler",
    durum: "aktif",
    sektor: "Teknoloji",
    talepBaslangic: "2026-03-24",
    talepBitis: "2026-03-26",
    arsFiyatiAlt: 8.50,
    arsFiyatiUst: 10.00,
    lotBuyuklugu: 100,
    araciKurum: "Garanti BBVA Yatırım",
    toplamArzLot: 5000000,
    bireyselPayYuzde: 50,
    kapLinki: "https://kap.org.tr",
    aciklama: "Metropal Kurumsal Hizmetler A.Ş., kurumsal müşterilere yazılım ve dijital dönüşüm hizmetleri sunmaktadır. 2015 yılında kurulan şirket, 500'den fazla kurumsal müşteriye hizmet vermektedir.",
    piyasaDegeri: 500000000,
  },
  {
    id: "btest-btest-2026",
    ticker: "BTEST",
    sirketAdi: "Bitest Yazılım ve Teknoloji A.Ş.",
    slug: "bitest-yazilim-teknoloji",
    durum: "yaklasan",
    sektor: "Yazılım",
    talepBaslangic: "2026-04-02",
    talepBitis: "2026-04-04",
    arsFiyatiAlt: 15.00,
    arsFiyatiUst: 18.00,
    lotBuyuklugu: 100,
    araciKurum: "İş Yatırım",
    toplamArzLot: 2000000,
    bireyselPayYuzde: 40,
    kapLinki: "https://kap.org.tr",
    aciklama: "Bitest Yazılım, Türkiye'nin önde gelen test otomasyon ve kalite güvence yazılımları şirketidir.",
    piyasaDegeri: 360000000,
  },
  {
    id: "fgrup-finans-2026",
    ticker: "FGRUP",
    sirketAdi: "F Finans Grubu A.Ş.",
    slug: "f-finans-grubu",
    durum: "yaklasan",
    sektor: "Finans",
    talepBaslangic: "2026-04-10",
    talepBitis: "2026-04-12",
    arsFiyatiAlt: 5.20,
    arsFiyatiUst: 6.50,
    lotBuyuklugu: 100,
    araciKurum: "Yapı Kredi Yatırım",
    toplamArzLot: 8000000,
    bireyselPayYuzde: 60,
    kapLinki: "https://kap.org.tr",
    aciklama: "F Finans Grubu, bireysel ve kurumsal finansman çözümleri sunan yenilikçi bir fintech şirketidir.",
    piyasaDegeri: 520000000,
  },
  {
    id: "eners-enerji-2026",
    ticker: "ENERS",
    sirketAdi: "Eners Yenilenebilir Enerji A.Ş.",
    slug: "eners-yenilenebilir-enerji",
    durum: "tamamlandi",
    sektor: "Enerji",
    talepBaslangic: "2026-03-10",
    talepBitis: "2026-03-12",
    arsFiyatiAlt: 12.00,
    arsFiyatiUst: 14.00,
    lotBuyuklugu: 100,
    araciKurum: "Denizbank Yatırım",
    toplamArzLot: 3500000,
    bireyselPayYuzde: 45,
    kapLinki: "https://kap.org.tr",
    aciklama: "Eners Yenilenebilir Enerji, güneş ve rüzgar enerjisi alanında Türkiye genelinde projeler geliştirmektedir.",
    piyasaDegeri: 490000000,
  },
  {
    id: "saglt-saglik-2026",
    ticker: "SAGLT",
    sirketAdi: "Sağlıktek Medikal Teknoloji A.Ş.",
    slug: "sagliktek-medikal-teknoloji",
    durum: "basvuru-surecinde",
    sektor: "Sağlık",
    talepBaslangic: "2026-03-25",
    talepBitis: "2026-03-27",
    arsFiyatiAlt: 22.00,
    arsFiyatiUst: 25.00,
    lotBuyuklugu: 100,
    araciKurum: "Akbank Yatırım",
    toplamArzLot: 1500000,
    bireyselPayYuzde: 35,
    kapLinki: "https://kap.org.tr",
    aciklama: "Sağlıktek Medikal Teknoloji, hastane bilgi yönetim sistemleri ve tele-tıp çözümleri geliştirmektedir.",
    piyasaDegeri: 375000000,
  },
];

export const mockHaberler: Haber[] = [
  {
    id: "haber-1",
    baslik: "MCARD Halka Arz Başladı: 8.50-10.00 TL Fiyat Bandında Talep Topluyorlar",
    ozet: "Metropal Kurumsal Hizmetler A.Ş.'nin halka arzı bugün başladı. Garanti BBVA Yatırım aracılığıyla gerçekleştirilen arzda 5 milyon lot bireysel yatırımcılara sunuluyor.",
    slug: "mcard-halka-arz-basladi",
    yayinTarihi: "2026-03-24",
    kategori: "halka-arz",
    ilgiliArzId: "mcard-metropal-2026",
  },
  {
    id: "haber-2",
    baslik: "Nisan Ayında 3 Yeni Halka Arz Bekleniyor: BTEST, FGRUP ve Sürpriz İsim",
    ozet: "Sermaye piyasaları nisan ayında hareketlenmeye hazırlanıyor. Bitest Yazılım ve F Finans Grubu'nun yanı sıra KAP'ta izahnamesini açıklayan üçüncü bir şirket de beklentileri artırıyor.",
    slug: "nisan-halka-arz-beklentileri",
    yayinTarihi: "2026-03-23",
    kategori: "analiz",
  },
  {
    id: "haber-3",
    baslik: "SPK, Halka Arz Başvurularında Rekor: 2026'nın İlk Çeyreğinde 12 Şirket",
    ozet: "Sermaye Piyasası Kurulu verilerine göre 2026'nın ilk üç ayında 12 şirket halka arz başvurusunda bulundu. Bu rakam, 2025'in aynı dönemine göre %40 artışa işaret ediyor.",
    slug: "spk-halka-arz-basvuru-rekoru",
    yayinTarihi: "2026-03-20",
    kategori: "piyasa",
  },
];

export const durumRenk: Record<string, string> = {
  aktif: "bg-emerald-500/20 text-emerald-400 border-emerald-500/30",
  yaklasan: "bg-blue-500/20 text-blue-400 border-blue-500/30",
  tamamlandi: "bg-slate-500/20 text-slate-400 border-slate-500/30",
  ertelendi: "bg-red-500/20 text-red-400 border-red-500/30",
  "basvuru-surecinde": "bg-amber-500/20 text-amber-400 border-amber-500/30",
};

export const durumEtiket: Record<string, string> = {
  aktif: "Aktif",
  yaklasan: "Yaklaşan",
  tamamlandi: "Tamamlandı",
  ertelendi: "Ertelendi",
  "basvuru-surecinde": "Başvuru Süreci",
};
